### ISSUE TITLE
Error when use special character (ñ) in feature file

### ISSUE THREAD

**Issue by jimmy-collazos** [Telefonica/toolium#54]
The error is caused by logger format (don't use `u"...".format()`) in [behave/environment.py](https://github.com/Telefonica/toolium/blob/master/toolium/behave/environment.py#L198)

```
Exception UnicodeEncodeError: 'ascii' codec can't encode character u'ñ' in position 42: ordinal not in range(128)
Traceback (most recent call last):
  File "/usr/local/bin/behave", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/site-packages/behave/__main__.py", line 109, in main
    failed = runner.run()
  File "/usr/local/lib/python2.7/site-packages/behave/runner.py", line 672, in run
    return self.run_with_paths()
  File "/usr/local/lib/python2.7/site-packages/behave/runner.py", line 693, in run_with_paths
    return self.run_model()
  File "/usr/local/lib/python2.7/site-packages/behave/runner.py", line 483, in run_model
    failed = feature.run(self)
  File "/usr/local/lib/python2.7/site-packages/behave/model.py", line 523, in run
    failed = scenario.run(runner)
  File "/usr/local/lib/python2.7/site-packages/behave/model.py", line 919, in run
    runner.run_hook('after_scenario', runner.context, self)
  File "/usr/local/lib/python2.7/site-packages/behave/runner.py", line 405, in run_hook
    self.hooks[name](context, *args)
  File "environment.py", line 46, in after_scenario
    toolium_after_scenario(context, scenario)
  File "/usr/local/lib/python2.7/site-packages/toolium/behave/environment.py", line 136, in after_scenario
    bdd_common_after_scenario(context, scenario, scenario.status)
  File "/usr/local/lib/python2.7/site-packages/toolium/behave/environment.py", line 154, in bdd_common_after_scenario
    context_or_world.logger.info("The scenario '{0}' has passed".format(scenario.name))
UnicodeEncodeError: 'ascii' codec can't encode character u'\xf1' in position 42: ordinal not in range(128)
```

**Comment by rgonalo** [comment]
I've deleted all _format()_ conversions on logger calls.
Thanks @jimmy-collazos!
